language: cpp

env:
  - COMPILER="g++-5"
  - COMPILER="g++-4.6"
  - COMPILER="g++-4.7"
  - COMPILER="g++-4.4"
  - COMPILER="g++-4.8"
  - COMPILER="g++-4.9"
  - COMPILER="g++-4.5"
  - COMPILER="clang++-3.3"
  - COMPILER="clang++-3.4"

before_script:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:h-rayflood/llvm
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
  - sudo apt-get update -qq
  - sudo apt-get install --allow-unauthenticated $COMPILER
  - git clone https://github.com/CxxTest/cxxtest.git cxxtest-ro
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr

script:
  - export PATH="$PATH:$(pwd)/cxxtest-ro/bin"
  - ln -s cxxtest-ro/cxxtest cxxtest
  - cd test
  - make COMPILER=$COMPILER unix
